apiVersion: v1
kind: Pod
metadata:
  name: nginx-lvm-test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
       - mountPath: /datadir
         name: fio-vol-nginx
  volumes:
  - name: fio-vol-nginx
    persistentVolumeClaim:
      claimName: csi-lvmpv-test  
